apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: queryservice-faults
spec:
  hosts:
  - queryservice.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: queryservice.default.svc.cluster.local
    fault:
      abort:
        percent: 80
        httpStatus: 500
      delay:
        percent: 80
        fixedDelay: 9s