apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis-slave
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-slave
        role: slave
        tier: backend
        version: 4.0.12-0
    spec:
      containers:
      - name: redis-slave
        image: bitnami/redis:latest
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_REPLICATION_MODE
          value: "slave"
        - name: REDIS_MASTER_HOST
          value: "redis-master"
        - name: REDIS_MASTER_PORT_NUMBER
          value: "6379"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"           
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis-slave
    role: slave
    tier: backend
    version: 4.0.12-0
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis-slave
    role: slave
    tier: backend