apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
spec:
  selector:
    matchLabels:
      app: redis-master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        role: master
        tier: backend
        version: 4.0.12-0
    spec:
      containers:
      - name: redis-master
        image: bitnami/redis:latest
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: REDIS_REPLICATION_MODE
          value: master
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis-master
    role: master
    tier: backend
    version: 4.0.12-0
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis-master
    role: master
    tier: backend